Models/Tilausrivit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilausrivit
    {
        public int TilausriviID { get; set; }
        public Nullable<int> TilausID { get; set; }
        public Nullable<int> TuoteID { get; set; }
        public Nullable<int> Maara { get; set; }
        public Nullable<decimal> Ahinta { get; set; }
    
        public virtual Tilaukset Tilaukset { get; set; }
        public virtual Tuotteet Tuotteet { get; set; }
    }
}

Controllers/TilausrivitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TilausDB2.Models;

namespace TilausDB2.Controllers
{
    [CheckSession]
    public class TilausrivitController : Controller
    {
        private TilauksetEntities db = new TilauksetEntities();

        // GET: Tilausrivit
        public ActionResult Index()
        {
            var tilausrivit = db.Tilausrivit.Include(t => t.Tilaukset).Include(t => t.Tuotteet);
            return View(tilausrivit.ToList());
        }

        // GET: Tilausrivit/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tilausrivit tilausrivit = db.Tilausrivit.Find(id);
            if (tilausrivit == null)
            {
                return HttpNotFound();
            }
            return View(tilausrivit);
        }

        // GET: Tilausrivit/Create
        public ActionResult Create(int? id)
        {
            Tilausrivit tilausrivit = new Tilausrivit();

            tilausrivit.TilausID = id.GetValueOrDefault();

            ViewBag.TuoteID = new SelectList(db.Tuotteet, "TuoteID", "Nimi");
            return View(tilausrivit);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int TilausID, [Bind(Include = "TilausID,TuoteID,Maara,Ahinta")] Tilausrivit tilausrivit)
        {
            if (ModelState.IsValid)
            {
                                tilausrivit.TilausID = TilausID;

                db.Tilausrivit.Add(tilausrivit);
                db.SaveChanges();
                return RedirectToAction("Index", "Tilaukset");
            }

            ViewBag.TilausID = new SelectList(db.Tilaukset, "TilausID", "Toimitusosoite", tilausrivit.TilausID);
            ViewBag.TuoteID = new SelectList(db.Tuotteet, "TuoteID", "Nimi", tilausrivit.TuoteID);
            return View(tilausrivit);
        }

        // GET: Tilausrivit/Edit/5
        public ActionResult Edit(int? TilausID, int? TuoteID)
        {
            if (TilausID == null || TuoteID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var tilausrivitList = db.Tilausrivit.Where(tr => tr.TilausID == TilausID && tr.TuoteID == TuoteID).ToList();

            
            if (tilausrivitList.Count == 0)
            {
                return HttpNotFound();
            }

           
            var tilausrivit = tilausrivitList.First();

            ViewBag.TilausID = new SelectList(db.Tilaukset, "TilausID", "Toimitusosoite", tilausrivit.TilausID);
            ViewBag.TuoteID = new SelectList(db.Tuotteet, "TuoteID", "Nimi", tilausrivit.TuoteID);
            return View(tilausrivit);
        }


        // POST: Tilausrivit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TilausriviID,TilausID,TuoteID,Maara,Ahinta")] Tilausrivit tilausrivit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tilausrivit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Tilaukset");
            }
            ViewBag.TilausID = new SelectList(db.Tilaukset, "TilausID", "Toimitusosoite", tilausrivit.TilausID);
            ViewBag.TuoteID = new SelectList(db.Tuotteet, "TuoteID", "Nimi", tilausrivit.TuoteID);
            return View(tilausrivit);
        }

        // GET: Tilausrivit/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tilausrivit tilausrivit = db.Tilausrivit.Find(id);
            if (tilausrivit == null)
            {
                return HttpNotFound();
            }
            return View(tilausrivit);
        }

        // POST: Tilausrivit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tilausrivit tilausrivit = db.Tilausrivit.Find(id);
            db.Tilausrivit.Remove(tilausrivit);
            db.SaveChanges();
            return RedirectToAction("Index", "Tilaukset");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Tilausrivit/Create.cshtml
@model TilausDB2.Models.Tilausrivit

@{
    ViewBag.Title = "Tilaushallinta";
}

<h4>Lisää tuotteita</h4>


@using (Html.BeginForm("Create", "Tilausrivit", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Tilausrivit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.TilausID)
    @ViewBag.TilausID
    @*<div class="form-group">
            @Html.LabelFor(model => model.TilausID, "TilausID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TilausID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TilausID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.TuoteID, "TuoteID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TuoteID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TuoteID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Maara, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Maara, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Maara, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ahinta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ahinta, new { htmlAttributes = new { @class = "form-control", type = "decimal", step = "0,01" } })

            @Html.ValidationMessageFor(model => model.Ahinta, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />
    <div class="container">
        <div class="row">
            <div class="col-auto">
                <a class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="Takaisin" href="javascript:void(0);" onclick="history.go(-1);"><img src="~/Icons/arrow-left-circle.svg" width="24" height="24" /></a>
            </div>
            <div class="col-auto">
                <input class="btn btn-success" data-toggle="tooltip" data-placement="bottom" title="Talenna" type="image" src="~/Icons/save.svg" />
            </div>
        </div>
    </div>
    </div>
    }


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Views/Tilausrivit/Delete.cshtml
@model TilausDB2.Models.Tilausrivit

@{
    ViewBag.Title = "Poista";
}

<h2>Poista</h2>

<h3>Varmista tiedot ennenpoistoa!</h3>
<div>

    <hr />
    <dl class="dl-horizontal">

        <dt>@Html.DisplayNameFor(model => model.Tuotteet.Nimi)</dt>

        <dd>@Html.DisplayFor(model => model.Tuotteet.Nimi)</dd>

        <dt>@Html.DisplayNameFor(model => model.Maara)</dt>

        <dd>@Html.DisplayFor(model => model.Maara)</dd>

        <dt>@Html.DisplayNameFor(model => model.Ahinta)</dt>

        <dd>@Html.DisplayFor(model => model.Ahinta)</dd>

        <dt>@Html.DisplayNameFor(model => model.Tilaukset.Toimitusosoite)</dt>

        <dd>@Html.DisplayFor(model => model.Tilaukset.Toimitusosoite)</dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <br />
        <div class="container">
            <div class="row">
                <div class="col-auto">
                    <a class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="Takaisin" href="javascript:void(0);" onclick="history.go(-1);"><img src="~/Icons/arrow-left-circle.svg" width="24" height="24" /></a>
                </div>
                <div class="col-auto">
                    <input class="btn btn-danger" data-toggle="tooltip" data-placement="bottom" title="Poista" type="image" src="~/Icons/x.svg" />
                </div>
            </div>
        </div>
   
    }
</div>

Views/Tilausrivit/Details.cshtml
@model TilausDB2.Models.Tilausrivit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tilausrivit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Maara)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maara)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ahinta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ahinta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tilaukset.Toimitusosoite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tilaukset.Toimitusosoite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tuotteet.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tuotteet.Nimi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TilausriviID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Tilausrivit/Edit.cshtml
@model TilausDB2.Models.Tilausrivit

@{
    ViewBag.Title = "Muokkaa";
}

<h2> Muokkaa tilausriviä</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <section>
        <table class="table">
            <tr>
                <th>Tilaus nro</th>
                <th>Tuotenimike</th>
                <th>Asiakas</th>
            </tr>
            <tr>
                <th>@Model.TilausID</th>
                <th>@Model.Tuotteet.Nimi</th>
                <th>@Model.Tilaukset.Asiakkaat.Nimi</th>
            </tr>
        </table>
    </section>


    <div class="form-horizontal">
  
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TilausriviID)

        <div class="form-group">
            @Html.LabelFor(model => model.TilausID, "TilausID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TilausID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TilausID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TuoteID, "TuoteID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TuoteID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TuoteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maara, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maara, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maara, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ahinta, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ahinta, new { htmlAttributes = new { @class = "form-control", type = "decimal", step = "0,01" } })
                @Html.ValidationMessageFor(model => model.Ahinta, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />
        <div class="container">
            <div class="row">
                <div class="col-auto">
                    <a class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="Takaisin" href="javascript:void(0);" onclick="history.go(-1);"><img src="~/Icons/arrow-left-circle.svg" width="24" height="24" /></a>
                </div>
                <div class="col-auto">
                    <input class="btn btn-success" data-toggle="tooltip" data-placement="bottom" title="Talenna" type="image" src="~/Icons/save.svg" />
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Tilausrivit/Index.cshtml
@model IEnumerable<TilausDB2.Models.Tilausrivit>

@{
    ViewBag.Title = "Tilausrivit";
}

<h2>Tilausrivit</h2>

<p>
    @Html.ActionLink("Create New", "Luo")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Maara)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ahinta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tilaukset.Toimitusosoite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tuotteet.Nimi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Maara)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ahinta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tilaukset.Toimitusosoite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tuotteet.Nimi)
        </td>

        <td>

            <a class="btn btn-warning" data-toggle="tooltip" data-placement="bottom" title="Editoi" href="/Tilausrivit/Edit?id=@item.TilausriviID"><img src="~/Icons/pen.svg" width="12" height="12" /></a>

            <a class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="Lisätiedot" href="/Tilausrivit/Details?id=@item.TilausriviID"><img src="~/Icons/three-dots.svg" width="12" height="12" /></a>

            <a class="btn btn-danger" data-toggle="tooltip" data-placement="bottom" title="Poista" href="/Tilausrivit/Delete?id=@item.TilausriviID"><img src="~/Icons/x-circle.svg" width="12" height="12" /></a>
        </td>
    </tr>
}

</table>